# log4j.properties — hadoop-platform-lab
# Doble salida: consola (docker logs) + fichero rotado en ./data/logs/<servicio>
# (bind mount de HADOOP_LOG_DIR, ver compose.yaml).
log4j.rootLogger: INFO, stdout, rolling

log4j.appender.stdout: org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern: %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

log4j.appender.rolling: org.apache.log4j.RollingFileAppender
log4j.appender.rolling.File: ${hadoop.log.dir}/hadoop.log
log4j.appender.rolling.MaxFileSize: 64MB
log4j.appender.rolling.MaxBackupIndex: 10
log4j.appender.rolling.layout: org.apache.log4j.PatternLayout
log4j.appender.rolling.layout.ConversionPattern: %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Auditoría de seguridad (aplicable si se activan permisos/Kerberos)
log4j.logger.org.apache.hadoop.security.authority.ServiceAuthorizationLogger: WARN, audit
log4j.appender.audit: org.apache.log4j.RollingFileAppender
log4j.appender.audit.File: ${hadoop.log.dir}/hadoop-audit.log
log4j.appender.audit.MaxFileSize: 64MB
log4j.appender.audit.MaxBackupIndex: 5
log4j.appender.audit.layout: org.apache.log4j.PatternLayout
log4j.appender.audit.layout.ConversionPattern: %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Ruido de librerías
log4j.logger.org.apache.hadoop.util.NativeCodeLoader: WARN
log4j.logger.org.apache.zookeeper: WARN
log4j.logger.org.apache.hadoop.hdfs.server.blockmanagement.BlockStateChange: WARN
